logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://jalgo-eureka.herokuapp.com/eureka/}

server:
  port: ${PORT:5003}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:jalgo-submissions}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
